defaults: &defaults
  allow_jsonp: true
  redirect_after_activation: '/activation.html'
  
  portal_base_url: 'https://wack-a-doo.de'
  
  default_scope: '5dentity'

  cookie_name: 'ip_remember_token'
  
  token_expiration: '28800'
  
  redirect_whitelist: [
    "www.kostenlose-browsergames.de",
    "www.xbrowsergames.de",
    "www.browsergamer.de",
  ]
      
development:
  <<: *defaults

  portal_base_url: 'https://localhost'
  
test:
  <<: *defaults

production:
  <<: *defaults

staging_test:
  <<: *defaults

  portal_base_url: 'https://testround2.wack-a-doo.de'

  cookie_name: 'ip_testround2_remember_token'