defaults: &defaults
  allow_jsonp: true
  redirect_after_activation: '/activation.html'
  
  default_scope: '5dentity'

  cookie_name: 'ip_remember_token'
  
  token_expiration: 3600*8
      
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
