defaults: &defaults
  allow_jsonp: true
  redirect_after_activation: '/activation.html'
  
  default_scope: '5dentity'
  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
