---
pid: /var/run/identity_provider.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: development
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/identity_provider/current
socket: /var/run/identity_provider.sock