---
pid: /var/run/identity_provider_round2.pid
timeout: 30
wait: 30
log: log/thin/identity_provider_round2.log
max_conns: 1024
require: []

environment: round2
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/identity_provider_round2/current
socket: /var/run/identity_provider_round2.sock